### ISSUE TITLE
Can't connect to Telegram API server via SSL

### ISSUE THREAD

**Issue by oleg-sh** [puehcl/python-telegram-bot-api#1]
```
Traceback (most recent call last):
  File "bot2.py", line 14, in <module>
    .build().start()
  File "/home/null/bot2/telegram/botapi/bot.py", line 23, in start
    for update in self.connector.stream_updates():
  File "/home/null/bot2/telegram/botapi/connector.py", line 37, in stream_updates
    for update in self.get_updates():
  File "/home/null/bot2/telegram/botapi/connector.py", line 25, in get_updates
    jobj = self.get_raw_updates()
  File "/home/null/bot2/telegram/botapi/connector.py", line 22, in get_raw_updates
    timeout=self.longpolling_timeout)
  File "/home/null/bot2/telegram/botapi/connector.py", line 91, in _do_get
    json_response = requests.get(url, params=params, timeout=timeout).json()
  File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 330, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.4/http/client.py", line 1065, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1103, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 841, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 111, in connect
    timeout=self.timeout)
  File "/usr/lib/python3.4/socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
KeyboardInterrupt
```

My SSL is set up and working on my website but somehow I'm unable to establish the connection.
The SSL certificate is a free certificate from startssl.com 
During set up process I used this guide https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-with-a-free-signed-ssl-certificate-on-a-vps
Do I need additional configuration steps for the bot to work?

**Comment by puehcl** [comment]
Hm, all i can see from your stacktrace is that you interrupted it yourself while in _socket.getaddrinfo(...), does it halt at this point?

**Comment by oleg-sh** [comment]
When I run 'python3 bot2.py' I see no output until I interrupt it no matter how long I wait (and the bot doesn't reply of course).
The code of bot2.py is the echo sample.

**Comment by puehcl** [comment]
Ah, alright, have you set up a webhook for getting updates? The webhook method is currently not implemented in the python API. Otherwise i don't understand what you need the SSL certificate for.

**Comment by oleg-sh** [comment]
My bad. Do you mean there's no need for a certificate? I only installed it after I encountered this issue:

```
File "/usr/local/lib/python3.2/dist-packages/re
quests/packages/urllib3/connection.py", line 238,
 in connect                                      
    ssl_version=resolved_ssl_version)            
  File "/usr/local/lib/python3.2/dist-packages/re
quests/packages/urllib3/util/ssl_.py", line 279, 
in ssl_wrap_socket                               
    return context.wrap_socket(sock, server_hostn
ame=server_hostname)                             
  File "/usr/lib/python3.2/ssl.py", line 189, in 
wrap_socket                                      
    _context=self)                               
  File "/usr/lib/python3.2/ssl.py", line 272, in 
__init__                                         
    self.do_handshake()                          
  File "/usr/lib/python3.2/ssl.py", line 451, in 
do_handshake                                     
    self._sslobj.do_handshake()                  
KeyboardInterrupt
```

I just copied the files from github, added a file with my API key to the root folder and tried running echo code from the example... So I thought I needed SSL certificate.

**Comment by oleg-sh** [comment]
OK, I think I've found the main cause of the issue.
I tried saving the apikey.txt in both unicode and ansi but it only worked once I inserted the key into botbuilder.py code and deleted the file. Now it works perfectly.
Thanks for your help.

**Comment by puehcl** [comment]
ah ok, glad you worked it out :), gotta look into that
